### ISSUE TITLE
Concept for Guides 2.0

### ISSUE THREAD

**Issue by swilgosz** [hanami/guides#83]
### Overview

The guides for Hanami 1.3 become obsolete, so we should design the new version of the guides. However, we should also keep existing documentation working. 

**Here is the issue to track this update, with a list of what can be done.**

When deciding on this, we can asynchronously work on smaller chapters, adapting existing guides when it makes sense, and rewriting it completely when that approach applies.

### Todo

- [ ] Move the existing guides to `content/1.0` folder
- [ ] Redirect all exisitng routes to 1.0
- [ ] Create a `content/2.0` folder
- [ ] Update the sidebar to work with multiple nesting levels.
- [x] Come with a raw structure of chapters for new guides (to be tweaked later)

### The concept of documents structure

```
2.0
|_ GETTING STARTED
   |_ Guide assumptions. # What needs to be learnt before getting to this
   |_ What is Hanami?      # General concept, Philosophy, why it's special? (refer architecture overview)
   |_ Hello, Hanami           # Creating and running minimal working application
   |_ Quick Blog application # Listing and showing blog posts
   |_ Security                    # Basic authentication mechanisms.

|_ ARCHITECTURE
   |_ Overview     # List all the building blocks, show a diagram with data flow, link to more detailed sections.

|_ ROUTER
  |_ Overview
  |_ Basic Usage
  |_ ...
  |_ Testing
|_ ACTIONS
  |_ Overview
  |_ Basic Usage
  |_ ....
  |_ Testing
|_ VIEWS
  |_ Overview
  |_ Basic Usage
  |_ Layouts
  |_ Templates
  |_ Parts
  |_ ....
  |_ Testing
|_ Validations
  |_ Overview
  |_ Basic Usage
  |_ ....
  |_ Testing
|_ Persistance
  |_ Overview
  |_ Relations
  |_ Repositories
  |_ Structs
  |_ ...
  |_ Testing
|_ Slices
  |_ Overview
  |_ Basic Usage
  |_ ....
  |_ Testing
|_ Assets
  |_ Overview
  |_ Basic Usage
  |_ ....
  |_ Testing
|_ Utils
  |_ Overview
  |_ Basic Usage
  |_ ....
  |_ Testing
|_ Helpers
  |_ Overview
  |_ Basic Usage
  |_ ....
  |_ Testing
|_ Mailers
  |_ Overview
  |_ Basic Usage
  |_ ....
  |_ Testing
|_ Command Line
  |_ Overview
  |_ Basic Usage
  |_ ....
  |_ Testing
|_ Scaling UP
  |_ Manageable monolith
  |_ Splitting application into microservices
|_ Upgrade Notes
```

**Comment by cllns** [comment]
Thanks for putting this work in! 

```
|_ GETTING STARTED
   |_ Guide assumptions. # What needs to be learnt before getting to this
   |_ What is Hanami?      # General concept, Philosophy, why it's special? (refer architecture overview)
   |_ Hello, Hanami           # Creating and running minimal working application
   |_ Quick Blog application # Listing and showing blog posts
   |_ Security                    # Basic authentication mechanisms.
```

I really like the current set up where the ["Getting Started" guide is all on one page](https://guides.hanamirb.org/introduction/getting-started/). It basically encompasses these first four sections. While I think the Philosophy and such are important, I think it's more important to get people going first, and they can see the philosophy in action. We can introduce the concepts as we get to them, too. For example, there's a link from "single class" to the wikipedia page for Single-responsibility principle.  I also like Bookshelf as the sample app instead of Blog, it's a bit more unique :) 

I think authentication is a good idea to include a guide for (just HTTP basic auth, maybe some notes about how to approach more advanced authentication), but it should be separate. Maybe in the "Scaling up" section, which could be named something generic like "Growing your app" or even "Extras"

**Comment by swilgosz** [comment]
@cllns , This would simplify the setup, but it would be nice to allow people to access the differrent parts from the sidebar, and urls to each section. 

we could do big one-file chapters for now to not require too much changes in the implementation just to write guides for 2.0.

I will follow your suggestion to not be blocked by files structure and just write some stuff;).

Thanks!

**Comment by swilgosz** [comment]
Moved to internal trello board.
